#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# # Run solver
# runApplication solids4Foam

# Run solver
runApplication pySolids4Foam

# ----------------------------------------------------------------- end-of-file

